services:
  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - network

  app:
    image: gopenux-flask-api
    container_name: container_app
    environment:
      - MONGO_URI=${MONGO_URI}   
    ports:
      - "5000:5000"   
    depends_on:
      - mongo
    networks:
      - network

  mongo:
    image: mongo:latest
    container_name: container_mongo
    ports:
      - "27017:27017"
    networks:
     - network 

networks:
  network:
    driver: bridge
